Brief design document about the job worker service
kaciulis/job-worker-service pull request #1
Opened 2021-09-13 17:24 UTC by kaciulis

2021-09-13 18:45 UTC, zmb3 requested changes

2021-09-13 18:45 UTC, zmb3 commented on README.md
> +The library is a go package that communicates with the operating system via the `os/exec` package and linux system calls that are required to run isolated and resource limited jobs. The library can s
Is a job that is manually stopped considered to be `finished` or `failed`? How can you tell the difference between a job that ran to completion and a job that was stopped prematurely?

2021-09-13 18:45 UTC, zmb3 commented on README.md
> +The API is based on gRPC (grpc remote procedure call) which uses HTTP/2 as its application layer transport. The gRPC methods correlate with the functionality of the library - you can start/stop a pro
It would be nice to include the .proto file you plan to use so we can get an idea for what it will be like to interact with the job worker service.

2021-09-13 18:45 UTC, zmb3 commented on README.md
> +##Alternatives
I like this section 👍 

It would be even better if for each of these alternatives that you considered and decided not to pursue, you included the reasoning why.

2021-09-13 18:45 UTC, zmb3 commented on README.md
> +A job can no longer be streamed if it has stopped (finished or failed) execution.
You can still view a job's output after it completes, right?

2021-09-13 18:45 UTC, zmb3 commented on README.md
> +No namespaces will be mounted, not even the proc namespace, so expect the output or execution of the job to work accordingly.
What does it mean to mount a namespace?

2021-09-13 18:45 UTC, zmb3 commented on README.md
> +### The Library
I'd like to see a little bit more about the library. What types and methods will it expose? What will the streaming interface look like?

2021-09-13 22:29 UTC, kaciulis commented on README.md
> +The library is a go package that communicates with the operating system via the `os/exec` package and linux system calls that are required to run isolated and resource limited jobs. The library can s
This was an oversight. For some reason, despite already talking about stopping the Job (and it’s also one of the requirements!) - totally forgot to include the stopped status.

2021-09-13 22:29 UTC, kaciulis commented on README.md
> +The API is based on gRPC (grpc remote procedure call) which uses HTTP/2 as its application layer transport. The gRPC methods correlate with the functionality of the library - you can start/stop a pro
I included the .proto file in the proto directory

2021-09-13 22:30 UTC, kaciulis commented on README.md
> +A job can no longer be streamed if it has stopped (finished or failed) execution.
Sorry, this line is not really needed. Don’t know why I would restrict this. In most cases You would most likely WANT to see the output of the job, especially if it failed. You will be able to stream the output after the execution or after it is stopped.

2021-09-13 22:31 UTC, kaciulis commented on README.md
> +No namespaces will be mounted, not even the proc namespace, so expect the output or execution of the job to work accordingly.
Mental lapse… was thinking about the PID namespace and was trying to write about the procfs. Sorry about that one :D

2021-09-13 22:32 UTC, kaciulis commented on README.md
> +### The Library
Added it as a snippet, this is how i imagine the libraries interface for now

2021-09-13 22:40 UTC, zmb3 commented on README.md
> +	Status *Status       // Status object of the given job
Should all these fields be exported? How will you prevent clients from concurrently modifying the jobs?

2021-09-14 01:20 UTC, russjones commented on README.md
> +Jobs will be run with their own dedicated PID/Mount/Network namespaces. This will be done by starting the job process from within a forked process that is cloned with the corresponding Clone flags. T
Can you provide a few more details, how will you pass information to the forked process?

2021-09-14 01:20 UTC, russjones commented on proto/jobservice.proto
> +  rpc Stop (JobRequest) returns (StopResponse) {}
How do you plan to stop a process?

2021-09-14 01:20 UTC, russjones commented on proto/jobservice.proto
> +}
Might want to include exit code as well because the exact exit code gives the caller information as well.

2021-09-14 01:20 UTC, russjones commented on README.md
> +The library is a go package that communicates with the operating system via the `os/exec` package and linux system calls that are required to run isolated and resource limited jobs. The library can s
Can you talk a bit more on how you will implement streaming? You have to support multiple clients streaming output from the same job.

2021-09-14 18:15 UTC, kaciulis commented on README.md
> +	Status *Status       // Status object of the given job
Sorry, non of these fields should be exported, they should only be  accessible for other packages via getter methods. At of now I think only the id and the status/exit codes are relevant, so only these two getters are required. The status/exit codes getter could live under a method called GetStatus() (int, int) - which should not return the Status object itself, but instead only the codes - this is because Status is  mutable and should be accessed, stored and changed with a sync primitive, in this case a Mutex or RWMutex.

2021-09-14 18:16 UTC, kaciulis commented on README.md
> +Jobs will be run with their own dedicated PID/Mount/Network namespaces. This will be done by starting the job process from within a forked process that is cloned with the corresponding Clone flags. T
Added detail about passing info to the forked process in the Process isolation part. Also added an alternative for passing specific run parameters.

2021-09-14 18:16 UTC, kaciulis commented on proto/jobservice.proto
> +  rpc Stop (JobRequest) returns (StopResponse) {}
By sending a SIGINT signal to the forked process, it will clean up and interrupt the jobs process. Added this detail to the library part

2021-09-14 18:16 UTC, kaciulis commented on proto/jobservice.proto
> +}
Yeah, totally makes sense - they’re added!

2021-09-14 18:16 UTC, kaciulis commented on README.md
> +The library is a go package that communicates with the operating system via the `os/exec` package and linux system calls that are required to run isolated and resource limited jobs. The library can s
I added a brief explanation of the streaming logic and some example code.

2021-09-14 18:33 UTC, zmb3 commented on README.md
> +The library is a go package that communicates with the operating system via the `os/exec` package and linux system calls that are required to run isolated and resource limited jobs. The library can s
Thanks for the updates. I'm curious how you'll handle canceling a stream with this approach, as your writes will block until all readers complete. Could you elaborate on this?

I also have concerns about sending the same underlying `[]byte` to streaming clients.  These clients won't have access to your `bufferMux`, so how will you ensure that clients aren't reading (or worse, writing) to the stream as the job output is flowing?

2021-09-15 00:50 UTC, russjones approved these changes

2021-09-15 15:52 UTC, kaciulis commented on README.md
> +The library is a go package that communicates with the operating system via the `os/exec` package and linux system calls that are required to run isolated and resource limited jobs. The library can s
Your concerns and comments are totally correct! I took the liberty of extending the example functionality that should solve all of your provided questions. Please look at the extension of the code and the explanation.   So first - blocking. All byte array sends in this context should always be invoked in a nonblocking manner - in a goroutine. Regarding the canceling of a stream - if we’re talking about the end of the process, I added a done channel to the StreamingChannel struct so that the listener could know when the stream has ended, if the listener stops listening then a method LeaveStream is invoked.   Second - sending the same underlying byte array is definitely troublesome and risky to say the least. To address this - I added a channel to the JobOutputStream struct to not block or slow down the Write function. Since now the listening of the channel happens in a goroutine, both the Writing to the buffer and sending of the bytes to all of the listening stream channels happens with a lock and unlock on the bufferMux. I still exposed the channels with GetBytes() and Done() from the StreamChannel, but I added the receiver cast (<-chan) to the return of these methods. Note - there are other ways to do this, for example the GetBytes() method could return just the []bytes and be a blocking call from the listeners perspective with a simple `return <-s.channel` instead of `return s.channel`

2021-09-15 15:54 UTC, zmb3 approved these changes
Thanks for addressing my questions! Feel free to proceed!

2021-09-15 15:59 UTC, merged